[project]
name = "HiveOS-solar-miner"
version = "0.1.0"
description = "Software to start HiveOS miner based of solar generation"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.6.6"
pycryptodome = ">=3.10.4,<3.11"
python-dotenv = ">=1.0.0,<1.1"
requests = ">=2.28.1,<2.29"
numpy = ">=1.19.5,<1.20"

